### ISSUE TITLE
Error when running the first example

### ISSUE THREAD

**Issue by matteodefelice** [ENSYSTRA/EU-SES#13]
I have just installed `EU-SES` on my Ubuntu WSL machine. I have followed the instructions and I was running the basic example in the README page with a single area (`Austria`). 

When running the line `example.create_regions('poli_regions')` I get this error:
```
In [14]: example.create_regions('poli_regions')
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-14-fead8f9bba95> in <module>
----> 1 example.create_regions('poli_regions')

/mnt/c/Users/matte/local_work/EU-SES/euses/components.py in create_regions(self, method, area_factor, initial_val, initial_seed, disaggr_var, aggr_var)
    175
    176
--> 177         class_regions = [zones.loc[c].id.to_list() for c in class_regions_int]
    178
    179         ds = aggregation(ds,class_regions,aggr_var)

UnboundLocalError: local variable 'class_regions_int' referenced before assignment
```
Do you have any idea on the cause of this error?

**Comment by chrisflei** [comment]
Thanks for raising this issue. The naming of the classification option ('poli_regions') was wrong in the Readme file. This has now been corrected. Please note you can also find more examples in the Three case studies.ipynb jupyter notebook.

**Comment by matteodefelice** [comment]
solved, thanks!
